Instance:		BDRMessageBundleBirthingExample
InstanceOf: 	BDRMessageBundle
Description: 	"Example BDR Message Birthing Bundle"
Usage: #example
* meta.profile = "http://hl7.org/fhir/us/birthdefectreporting/StructureDefinition/bdr-bundle"
* id = "BDRMessageBundleBirthingExample"
* identifier.value = "45678"
* type = #message
* timestamp = "2020-07-15T13:28:17.239+05:00"
* entry[0].fullUrl = "http://acme.com/ehr/fhir/MessageHeader/BDRMessageHeaderBirthingExample"
* entry[=].resource = BDRMessageHeaderBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Condition/ReportableDiagnosisBirthingExample"
* entry[=].resource = ReportableDiagnosisBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Organization/HospitalSubmitterExample"
* entry[=].resource = HospitalSubmitterExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Patient/PatientNewbornExample"
* entry[=].resource = PatientNewbornExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/RelatedPerson/MotherRelatedPersonBirthingExample"
* entry[=].resource = MotherRelatedPersonBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/RelatedPerson/FatherRelatedPersonBirthingExample"
* entry[=].resource = FatherRelatedPersonBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherEducationBirthingExample"
* entry[=].resource = MotherEducationBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/FatherEducationBirthingExample"
* entry[=].resource = FatherEducationBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/InfantLivingBirthingExample"
* entry[=].resource = InfantLivingBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherAlcoholUseBirthingExample"
* entry[=].resource = MotherAlcoholUseBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherExposureBirthingExample"
* entry[=].resource = MotherExposureBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherDrugUseBirthingExample"
* entry[=].resource = MotherDrugUseBirthingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/RelatedPerson/ResponsiblePartyExample"
* entry[=].resource = ResponsiblePartyExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Patient/MotherPatientExample"
* entry[=].resource = MotherPatientExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PregnancyOutcomeExample"
* entry[=].resource = PregnancyOutcomeExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/AdmissionToNicuExample"
* entry[=].resource = AdmissionToNicuExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/HeadCircumferenceExample"
* entry[=].resource = HeadCircumferenceExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherHeightExample"
* entry[=].resource = MotherHeightExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PreviousPretermBirthsExample"
* entry[=].resource = PreviousPretermBirthsExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PrimaryInsuranceExample"
* entry[=].resource = PrimaryInsuranceExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/TotalPregnanciesExample"
* entry[=].resource = TotalPregnanciesExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/ApgarFiveMinuteExample"
* entry[=].resource = ApgarFiveMinuteExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/ApgarTenMinuteExample"
* entry[=].resource = ApgarTenMinuteExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/LaborOnsetExample"
* entry[=].resource = LaborOnsetExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/BirthsNowLivingExample"
* entry[=].resource = BirthsNowLivingExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/BirthsNowDeadExample"
* entry[=].resource = BirthsNowDeadExample
//* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/GestationalAgeExample"
//* entry[=].resource = GestationalAgeExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/FetalDeathsExample"
* entry[=].resource = FetalDeathsExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherDeliveryWeightExample"
* entry[=].resource = MotherDeliveryWeightExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/MotherPrepregnancyWeightExample"
* entry[=].resource = MotherPrepregnancyWeightExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/LiveBirthsThisPregnancyExample"
* entry[=].resource = LiveBirthsThisPregnancyExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PrenatalVisitsExample"
* entry[=].resource = PrenatalVisitsExample
//* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PlaceOfBirthExample"
//* entry[=].resource = PlaceOfBirthExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PluralityExample"
* entry[=].resource = PluralityExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/OtherOutcomesExample"
* entry[=].resource = OtherOutcomesExample
* entry[+].fullUrl = "http://acme.com/ehr/fhir/Observation/PreviousCesareansExample"
* entry[=].resource = PreviousCesareansExample